### ISSUE TITLE
Serverside crash

### ISSUE THREAD

**Issue by KaseiFR** [oldjunyi/LightLevelOverlayReloaded#1]
Hello!

Being a client side only mod, LightLevelOverlayReloaded prevent Minecraft servers from running when present at the server side. It's especially annoying for modpacks without a specific server archive.

Forge may be able to disable this mod automatically when on a server. Could you look into it?

**Comment by oldjunyi** [comment]
OK, I will fix it.

**Comment by KaseiFR** [comment]
Thanks

**Comment by oldjunyi** [comment]
Done, please check http://minecraft.curseforge.com/projects/light-level-overlay-reloaded
