### ISSUE TITLE
Numbers do not show up at all on vanilla Bedrock

### ISSUE THREAD

**Issue by Lothrazar** [oldjunyi/LightLevelOverlayReloaded#10]
I was playing in 1.12.1 minecraft

![2017-08-07_14 07 42](https://user-images.githubusercontent.com/621529/29045868-ef690992-7b79-11e7-8d42-7fb4d1f0e725.png)

**Comment by oldjunyi** [comment]
It is intended, monster will not spawn on bedrock.
