### ISSUE TITLE
Game crashed when I hit F4 after trying to change mode to Minimal

### ISSUE THREAD

**Issue by bloodconfetti** [oldjunyi/LightLevelOverlayReloaded#23]
[crash-2019-08-04_03.51.06-client.txt](https://github.com/oldjunyi/LightLevelOverlayReloaded/files/3464839/crash-2019-08-04_03.51.06-client.txt)
[crash-2019-08-04_03.49.09-client.txt](https://github.com/oldjunyi/LightLevelOverlayReloaded/files/3464840/crash-2019-08-04_03.49.09-client.txt)

Your mod is wonderful and so useful! Unfortunately had to remove it. When I did, pushing F4 no longer crashed the game. There are two crash reports because I attempted to change it back to 'Standard' mode, since that had previously been working, but it still crashed. Maybe I just entered it wrong; I really don't understand all of this coding stuff, but I did just as your instructions said. Sorry for the trouble.

**Comment by oldjunyi** [comment]
Thanks for report. Will fix it asap.

--
姜凯 (Kai Jiang)

在 2019年8月4日，下午7:10，bloodconfetti <notifications@github.com<mailto:notifications@github.com>> 写道：


crash-2019-08-04_03.51.06-client.txt<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foldjunyi%2FLightLevelOverlayReloaded%2Ffiles%2F3464839%2Fcrash-2019-08-04_03.51.06-client.txt&data=02%7C01%7C%7C49c83c9b3bd34deb892208d718cc5628%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637005138207479636&sdata=T6KW2ZtemeokhNzFHXsCs3MaHQ7cOB%2FQVn%2BWKtRJuPk%3D&reserved=0>
crash-2019-08-04_03.49.09-client.txt<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Foldjunyi%2FLightLevelOverlayReloaded%2Ffiles%2F3464840%2Fcrash-2019-08-04_03.49.09-client.txt&data=02%7C01%7C%7C49c83c9b3bd34deb892208d718cc5628%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637005138207489644&sdata=fxOHsVlwDQz4XDP24Z4PM0%2BBfuz%2BjfdG553vUadAH6s%3D&reserved=0>

**Comment by bloodconfetti** [comment]
Thank you!! :)

**Comment by oldjunyi** [comment]
Should be resolved in https://www.curseforge.com/minecraft/mc-mods/light-level-overlay-reloaded/files/2754639
Feel free to reopen this thread if you are still encountering this issue.
