### ISSUE TITLE
NPE in "minimal" mode

### ISSUE THREAD

**Issue by Knito58** [oldjunyi/LightLevelOverlayReloaded#24]
Everything was fine but I remembered that there was a mode which only showed the red numbers when necessary. I stopped the game, went to the config folder and changed name = "standard" to name = "minimal".
After the restart and reload of the world I hit the LLOR-Key (F6 in my case) and the game crashed.

MC 1.14.4 Forge 28.0.40 LLOR 1.2.2
https://pastebin.com/XK0CtWj7

**Comment by oldjunyi** [comment]
Ah, I see. I forgot to test this flow before. Let me get a fix for it.

--
姜凯 (Kai Jiang)

在 2019年8月5日，下午5:49，Konitor <notifications@github.com<mailto:notifications@github.com>> 写道：


Everything was fine but I remembered that there was a mode which only showed the red numbers when necessary. I stopped the game, went to the config folder and changed name = "standard" to name = "minimal".
After the restart and reload of the world I hit the LLOR-Key (F6 in my case) and the game crashed.

MC 1.14.4 Forge 28.0.40 LLOR 1.2.2
https://pastebin.com/XK0CtWj7<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpastebin.com%2FXK0CtWj7&data=02%7C01%7C%7C0b20a27a7c8c4cd23a3408d7198a2671%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637005953447989231&sdata=9Re81%2B%2FwTelsfmUX%2FCy2B1K%2BWfB4GvfDnBKgaaqqmVI%3D&reserved=0>

**Comment by oldjunyi** [comment]
This looks to be a different issue related with multithreading. Could you double confirm that it is happening when you are pressing the LLOR-Key? @Knito58

The log shows the crash happened in server chunk thread in minecraft's own code base, and there is no sign of LLOR involving it.

**Comment by Knito58** [comment]
Yes that is the case. The crash happened after hitting the LLOR-key but then:
The crash persists. Changing config value back to "standard" or even uninstall the mod:
The world is not playable any more. After one second it crashes with the same NPE and no trace back to LLOR. The only hint I had was the crash after changing the setting to "minimal" and hitting my key. The crash report only shows MC code, as it seems. Please understand that I strongly believe that the minimal mode did st crazy and that the new world I did start now has no LLOR atm.
I even updated Forge to 28.0.41 but no help from that side.

I wish you the very best success in fixing this one.

**Comment by oldjunyi** [comment]
Thanks. Let me move the light level calculation back to main thread. It should solve this issue if it is cause by LLOR.

**Comment by oldjunyi** [comment]
Released 1.2.3

**Comment by Knito58** [comment]
Sorry wanted to check it out but am on Forge 28.0.45 now and the version 1.2.3 of LLOR won't load.

**Comment by oldjunyi** [comment]
:(
Forge 28.0.45 changed the source code location of tick event (https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.0.45/forge-1.14.4-28.0.45-changelog.txt).

Let compile the code again use the newest Forge.

**Comment by Knito58** [comment]
Can confirm bug gone :)
