### ISSUE TITLE
Suggestion - Make overlay numbers yellow where tiles are exposed to daylight..

### ISSUE THREAD

**Issue by ariosos** [oldjunyi/LightLevelOverlayReloaded#3]
One thing I miss from the light level indicator in prior versions (1,7.10 and earlier) where the green/yellow/red X markers. I liked this for several reasons -

1 - It didn't feel as obtrusive (the numbers are thick and take up the entire block - making it harder to see the terrain I'm working with).
2 - Yellow X's indicated blocks that were open to the sunlight, which was good if I wanted to light some of the outside, and there was an area with red X's there were say, under an overhang.
3 - Related to the first one, I didn't see the overlay where I had torch light, making it less confusing to find a red or yellow X that I missed.

Perhaps add an extra key (F5?), or F4 could cycle through several modes of overlays, one being raw light level, and the other being "skylight level".

**Comment by oldjunyi** [comment]
Currently you can use Shift + F4 to switch between "Torch Light Only" and "Torch Light + Sky Light" mode. I will consider to add a "Mixed" mode contains yellow numbers in next release.
And for X markers, you can use a resource pack to change the numbers to X markers.

**Comment by oldjunyi** [comment]
Added yellow numbers in advanced mode. For details, please check the change log: http://minecraft.curseforge.com/projects/light-level-overlay-reloaded/files/2312553
