### ISSUE TITLE
Overlay not showing

### ISSUE THREAD

**Issue by SOLIJA** [oldjunyi/LightLevelOverlayReloaded#8]
The overlay is not showing up on the ground when hitting F4.

When I hit Shift + F4 it switches to advanced, etc.

I made sure the binding was correct.

I currently run Sildur's shaders and I read a comment on curse saying that it doesn't work with Sildur's shaders.

Is that the issue, and is it going to be fixed?

**Comment by oldjunyi** [comment]
It has some conflict with shader mod, I will try to fix it in the next version.

发件人: SOLIJA<mailto:notifications@github.com>
发送时间: 2017年3月11日 15:00
收件人: oldjunyi/LightLevelOverlayReloaded<mailto:LightLevelOverlayReloaded@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [oldjunyi/LightLevelOverlayReloaded] Overlay not showing (#8)


The overlay is not showing up on the ground when hitting F4.

When I hit Shift + F4 it switches to advanced, etc.

I made sure the binding was correct.

I currently run Sildur's shaders and I read a comment on curse saying that it doesn't work with Sildur's shaders.

Is that the issue, and is it going to be fixed?

―

**Comment by SOLIJA** [comment]
Thank you for the quick response, I will keep an eye for the new version.
